### ISSUE TITLE
about Synthesize ProciGen

### ISSUE THREAD

**Issue by albertcity** [xiexh20/ProciGen#1]
Hello,
I am a PhD and interested in generating large-scale human-object interaction dataset for training a VLM. We have read your paper and found it really helpful for our goal. However, the released dataset (with 1M samples) does not meet the extreme demands we have for data, since we are planning to training a VLM from scratch (with pre-training stage).

I have noticed that the code for synthetising ProciGen has not been open-sourced yet (according to the README.md in this repo). I am wondering is there any plan to open-source it? 

Best regards.

**Comment by xiexh20** [comment]
Hi,  thank you for your interest. 

Yes, the code will be released. I am still cleaning up the code as it involves lots of repos. Hopefully it will be available after CVPR deadline.

Best,
Xianghui

**Comment by xiexh20** [comment]
Synthesis code released! Please check: https://github.com/xiexh20/ProciGen?tab=readme-ov-file#synthesize-procigen
