### ISSUE TITLE
When will the code for the synthetic dataset be released?

### ISSUE THREAD

**Issue by xishuxishu** [xiexh20/ProciGen#2]
Hi, thank you for sharing this amazing project! I was wondering if there’s a timeline for releasing the code for the synthetic dataset mentioned in the repository. Looking forward to your update. Thanks in advance!

**Comment by xiexh20** [comment]
thank you for your interest!
I am working on the code these days and it will be released by next week.

**Comment by xiexh20** [comment]
Synthesis code released! Please check: https://github.com/xiexh20/ProciGen?tab=readme-ov-file#synthesize-procigen
